# -*- coding: utf-8 -*-
"""ml aqi .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeVgDNbAGp1Ce7f7v-UDibRQIoU4r6-9
"""

import requests
import pandas as pd
import time

TOKEN = "0419c8ac5bd983c13df15dc0c7c911732e306dc1"

cities = [
    "london",
    "new-york",
    "los-angeles",
    "paris",
    "beijing",
    "delhi",
    "tokyo",
    "seoul",
    "shanghai",
    "berlin"
]

data_list = []

print("Starting Data Collection from WAQI API...")

for city in cities:
    # 3. CONSTRUCT URL
    url = f"https://api.waqi.info/feed/{city}/?token={TOKEN}"

    try:
        response = requests.get(url)
        data = response.json()

        if data['status'] == 'ok':
            # Extract data
            result = data['data']
            iaqi = result.get('iaqi', {})

            # Create a row for this city
            row = {
                "City": city,
                "AQI": result.get('aqi', 'N/A'),
                "PM2.5": iaqi.get('pm25', {}).get('v', 'N/A'),
                "PM10": iaqi.get('pm10', {}).get('v', 'N/A'),
                "NO2": iaqi.get('no2', {}).get('v', 'N/A'),
                "SO2": iaqi.get('so2', {}).get('v', 'N/A'),
                "O3": iaqi.get('o3', {}).get('v', 'N/A'),
                "Lat": result.get('city', {}).get('geo', [None, None])[0],
                "Lon": result.get('city', {}).get('geo', [None, None])[1]
            }

            data_list.append(row)
            print(f"Success: {city} (AQI: {row['AQI']})")
        else:
            print(f"Error for {city}: Unknown Station")

    except Exception as e:
        print(f"Connection error for {city}: {e}")

    # Sleep for 1 second to respect API limits
    time.sleep(1)

# 4. SAVE TO CSV
if data_list:
    df = pd.DataFrame(data_list)
    df.to_csv("waqi_city_data.csv", index=False)
    print("\nSUCCESS! Data saved to 'waqi_city_data.csv'")
    print(df.head(10))
else:
    print("No data collected. Check your Token.")

df.columns
df['City']

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
try:
    df = pd.read_csv('city_day.csv')
    print("Dataset Loaded Successfully!")
except FileNotFoundError:
    print("ERROR: Please download the 'city_day.csv' file from Kaggle first.")


numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

df['Date'] = pd.to_datetime(df['Date'])


print("Data Cleaned. Generating Images...")

#viz1:
plt.figure(figsize=(10, 8))
sns.heatmap(df[['PM2.5', 'PM10', 'NO2', 'CO', 'SO2', 'O3']].corr(), annot=True, cmap='coolwarm')
plt.title("1. Correlation Between Pollutants")
plt.savefig("viz1_heatmap.png")
plt.close()

# viz2:
plt.figure(figsize=(8, 5))
sns.histplot(df['PM2.5'], bins=50, kde=True, color='purple')
plt.title("2. Distribution of PM2.5 Levels")
plt.savefig("viz2_histogram.png")
plt.close()

# viz3:
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['AQI'], color='orange')
plt.title("3. Boxplot of Air Quality Index (AQI)")
plt.savefig("viz3_boxplot.png")
plt.close()

# viz4:
plt.figure(figsize=(8, 5))
sns.scatterplot(x=df['NO2'], y=df['PM2.5'], alpha=0.3)
plt.title("4. NO2 vs PM2.5 Concentration")
plt.savefig("viz4_scatter.png")
plt.close()

# viz5:
city_name = df['City'].unique()[0]
subset = df[df['City'] == city_name]
plt.figure(figsize=(12, 5))
plt.plot(subset['Date'], subset['PM2.5'], label='PM2.5')
plt.title(f"5. PM2.5 Trends Over Time ({city_name})")
plt.legend()
plt.savefig("viz5_linechart.png")
plt.close()

# viz6:
avg_aqi = df.groupby('City')['AQI'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=avg_aqi.values, y=avg_aqi.index, palette='viridis')
plt.title("6. Top 10 Polluted Cities (Avg AQI)")
plt.savefig("viz6_barchart.png")
plt.close()

# viz7:
plt.figure(figsize=(10, 10))
sns.pairplot(df[['PM2.5', 'NO2', 'SO2', 'O3']].sample(500))
plt.savefig("viz7_pairplot.png")
plt.close()

# viz8:
plt.figure(figsize=(8, 5))
sns.violinplot(x=df['AQI'], color='cyan')
plt.title("8. Density Distribution of AQI")
plt.savefig("viz8_violin.png")
plt.close()

# viz9:
df['Month'] = df['Date'].dt.month
monthly_avg = df.groupby('Month')['PM2.5'].mean()
plt.figure(figsize=(8, 5))
monthly_avg.plot(kind='bar', color='green')
plt.title("9. Average PM2.5 Levels by Month (Seasonality)")
plt.xlabel("Month (1=Jan, 12=Dec)")
plt.savefig("viz9_seasonality.png")
plt.close()


def categorize_aqi(x):
    if x <= 50: return 'Good'
    elif x <= 100: return 'Moderate'
    else: return 'Poor'

aqi_cats = df['AQI'].apply(categorize_aqi).value_counts()
plt.figure(figsize=(6, 6))
plt.pie(aqi_cats, labels=aqi_cats.index, autopct='%1.1f%%', colors=['red', 'yellow', 'green'])
plt.title("10. Proportion of Air Quality Days")
plt.savefig("viz10_piechart.png")

# Extract day name and create a weekend boolean tag
df['DayOfWeek'] = df['Date'].dt.day_name()
df['IsWeekend'] = df['DayOfWeek'].isin(['Saturday', 'Sunday'])

#viz11
plt.figure(figsize=(8, 6))
sns.boxplot(x='IsWeekend', y='PM2.5', data=df, palette='cool')
plt.xticks([0, 1], ['Weekday (Mon-Fri)', 'Weekend (Sat-Sun)'])
plt.title("11. PM2.5 Levels: Weekday vs. Weekend")
plt.ylabel("PM2.5 Concentration")
plt.savefig("viz11_weekend_vs_weekday.png")
plt.close()

df['Year'] = df['Date'].dt.year
yearly_avg = df.groupby('Year')['AQI'].mean()

#viz12
plt.figure(figsize=(10, 6))
# Using a line plot with markers to show the progression
sns.lineplot(x=yearly_avg.index, y=yearly_avg.values, marker='o', color='darkred', linewidth=2)
plt.title("12. Average Annual AQI Trend (2015-2020)")
plt.ylabel("Average AQI")
plt.xlabel("Year")
plt.grid(True, linestyle='--')
plt.savefig("viz12_yearly_trend.png")
plt.close()

# Find the two most frequent cities in the dataset
top_2_cities = df['City'].value_counts().head(2).index.tolist()
city_A_name = top_2_cities[0]
city_B_name = top_2_cities[1]

# Create subsets
city_A = df[df['City'] == city_A_name]
city_B = df[df['City'] == city_B_name]

#viz13
plt.figure(figsize=(14, 6))
plt.plot(city_A.set_index('Date')['AQI'].resample('M').mean(), label=city_A_name, color='blue', alpha=0.7)
plt.plot(city_B.set_index('Date')['AQI'].resample('M').mean(), label=city_B_name, color='red', alpha=0.7)
plt.title(f"13. Monthly Average AQI Comparison: {city_A_name} vs. {city_B_name}")
plt.ylabel("Monthly Average AQI")
plt.legend()
plt.savefig("viz13_city_comparison.png")
plt.close()

#viz14
plt.figure(figsize=(9, 6))
sns.kdeplot(df['NO2'], shade=True, color='green')
plt.title("14. Density Distribution of Nitrogen Dioxide (NO2)")
plt.xlabel("NO2 Concentration")
plt.xlim(0, df['NO2'].quantile(0.99))
plt.savefig("viz14_no2_kde.png")
plt.close()


#viz15
plt.figure(figsize=(8, 6))
plt.hexbin(x=df['PM2.5'], y=df['PM10'], gridsize=40, cmap='inferno', mincnt=1)
plt.colorbar(label='Count of Observations')
plt.title("15. Hexbin Density: PM2.5 vs. PM10")
plt.xlabel("PM2.5")
plt.ylabel("PM10")
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.savefig("viz15_hexbin_pm25_pm10.png")
plt.close()

